export const DOSAGE_FORMS = [
  "Oral: Capsule/Tablet",
  "Oral: Gargle/Mouthwash",
  "Oral: Gum/Lozenge",
  "Oral: Liquid/Solution/Suspension",
  "Oral: Powder(granule)",
  "Oral: Sublingual spray/tab",
  "Topical: Paste",
  "Topical: Dressing",
  "Topical: Cream/Gel/Ointment/Lotion",
  "Topical: Patch/Tape",
  "Topical: Shampoo/Paint/Topical Solution",
  "Topical: Spray",
  "Ear drop/Cream/Ointment",
  "Eye Drop",
  "Eye Gel/Ointment",
  "Nasal Drop/Cream/Ointment",
  "Nasal spray",
  "Inhalation: Aerolizer",
  "Inhalation: Metered dose",
  "Inhalation: Nebulizer",
  "Inhalation: Other DPI",
  "Inhalation: Oxygen",
  "Injection: Amp/Vial",
  "Injection: prefilled",
  "Pessaries",
  "Patient controlled analgesia",
  "Enema",
  "Suppository",
  "Vaginal"
]

export const FREQUENCIES = [
  "Once Daily",
  "Once Daily PRN(when required)",
  "Twice Daily",
  "Twice Daily PRN",
  "Three Times Daily",
  "Three Times Daily PRN",
  "Four Times Daily",
  "Four Times Daily PRN",
  "Q12H",
  "Q12H PRN",
  "Q8H",
  "Q8H PRN",
  "Q6H",
  "Q6H PRN",
  "Q4H",
  "Q4H PRN",
  "Q2H",
  "Q2H PRN",
  "PRN/sos (when necessary)",
  "Alternate Days/less frequently",
  "Oxygen PRN",
  "Oxygen < 15 hrs",
  "Oxygen > 15 hrs",
  "Others"
]

export const INSTRUCTIONS = [
  "Break/crush tablet",
  "Dissolve tablet/powder",
  "Multiple units at once (e.g. 2 tabs, 2 puffs)",
  "Take at specific time (e.g. morning, night, 9am)",
  "Relation to food (e.g. after/before/with food)",
  "Variable dose(e.g. 1-2 caps, 2-3 puffs)",
  "Take with specific fluid",
  "Take/use as directed",
  "Tapering/increasing",
  "Alternating dose (e.g. one morning & two at night, one/two on alt days)"
]
